### ISSUE TITLE
Broken svg in demo.

### ISSUE THREAD

**Issue by fleeting** [defvayne23/SVGMarker#2]
The svg used in the demo is broken - http://codepen.io/defvayne23/pen/EVYGRw. I would suggest getting a svg and uploading it to CodePen as an asset and linking that way to avoid depending on a third party url.

**Comment by defvayne23** [comment]
File has been replaced with a CodePen asset.

**Comment by fleeting** [comment]
👍

**Comment by fleeting** [comment]
Might also be worth linking to some of our sites that currently use it to see it in the wild.
